# Generated by Django 2.2 on 2020-01-12 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
